trial_info:
  synth2_path: None
  test_fraction: 0.1
  batch_size: 2048
  num_clusters: 10
  cluster_dim: 5
  epochs: {'trial_meth': suggest_int, "low": 200 , "high": 500, "log": False}
  # epochs: 5
  z_dim: 126
  activation_function_str: 'sigmoid'
  lr: {'trial_meth': suggest_float, "low": 0.00001, "high": 0.005, "log": true} 
  weight_decay: {'trial_meth': "suggest_float", "low": 0.000001, "high": 0.01, "log": true}
  verbose: 1
  kl: true
  kl_weight: {'trial_meth': "suggest_float", "low": 0.0000000001, "high": 0.01, "log": true}
  seed: 1


n_trials: 10
out_path: "/dbfs/mnt/dseedsi/users/ton/synth_graphs/gridsearch/10k_trxn/bimlp_10k_trxn"