trial_info:
  dropout: {'trial_meth': suggest_float, "low": 0., "high": 0.2}
  num_layers: 2
  num_neighbors: {'trial_meth': suggest_int, "low": 5, "high": 25}
  epoch: {'trial_meth': suggest_int, "low": 1000, "high": 10000, "log": true}
  embedding_dim: 32
  lr: {'trial_meth': suggest_float, "low": 0.0001, "high": 0.005, "log": true}
  embed_path: 'embed/'
  verbose: 0
  num_test: 0.2
  batch_size: 36
  
n_trials: 100
out_path: "temp/gridsearch/graphsage_erdos"