trial_info:
  n_walks: {'trial_meth': suggest_int, "low": 1000, "high": 10000, "log": False}
  test_n_walks: 512
  batch_size: 512
  num_clusters: {'trial_meth': suggest_int, "low": 16 , "high": 128, "log": False} 
  cluster_emb_dim: {'trial_meth': suggest_int, "low": 16 , "high": 128, "log": False}
  mu_hidden_dim: 128
  l_w: {'trial_meth': suggest_int, "low": 4 , "high": 32, "log": False}
  num_epochs: {'trial_meth': suggest_int, "low": 500 , "high": 4000, "log": False}
  # num_epochs: {'trial_meth': suggest_int, "low": 5 , "high": 40, "log": False}
  minimum_walk_length: 2
  verbose: 1
  pca_components: {'trial_meth': suggest_int, "low": 16 , "high": 64, "log": False}
  config_path: "lstm_model/"
  lr: {'trial_meth': suggest_float, "low": 0.00001, "high": 0.005, "log": true} 
  kl_weight: {'trial_meth': suggest_float, "low": 0.00001, "high": 0.05, "log": true}
  dropout: {'trial_meth': suggest_float, "low": 0., "high": 0.3} 
  nb_lstm_layers: {'trial_meth': suggest_int, "low": 1, "high": 2} 
  weight_decay: {'trial_meth': "suggest_float", "low": 0.000001, "high": 0.01, "log": true}

n_trials: 100
out_path: "temp/gridsearch/ddpm_lstm"